4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:

1.Initialize an empty array with size 2X2.

In [ ]:
import numpy as np
empty_array = np.empty((2, 2))
print("Empty Array (2x2):\n", empty_array)


Empty Array (2x2):
 [[4.68115255e-310 0.00000000e+000]
 [2.84571044e+140 6.52041948e-310]]


2.Initialize an all one array with size 4X2.

In [ ]:
import numpy as np

array = np.ones((4, 2))
print(array)


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np

fill_value = 4
new_array = np.full((3,3),fill_value)
print("New array:\n", new_array)

New array:
 [[4 4 4]
 [4 4 4]
 [4 4 4]]


 4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np

reference_array = np.array([[9, 8], [4, 8]])
new_array = np.zeros_like(reference_array)
print("New Array:\n", new_array)

New Array:
 [[0 0]
 [0 0]]


 5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np

reference_array = np.array([[1,2],[3,4]])
new_array = np.ones_like(reference_array)
print("new array:\n", new_array)

new array:
 [[1 1]
 [1 1]]


 6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

new_list = [1,2,3,4]
numpy_array = np.array(new_list)
print("numpy array:\n", numpy_array)

numpy array:
 [1 2 3 4]


4.1.1 Problem- 2: Array Manipulation: Numerical Ranges and Array indexing:
 Complete the following tasks:

1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np

new_array = np.arange(10 , 50)
print(new_array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
 {Hint:look for np.reshape()}

In [ ]:
import numpy as np

matrix = np.arange(9). reshape(3,3)
print("3*3 matrix=\n",matrix)


3*3 matrix=
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


3.Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np

array = np.eye(3)
print("3*3 Identity matrix= \n", array)

3*3 Identity matrix= 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
 {Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np

random_array = np.random.random(30)
# array_mean = random_array.mean()
array_mean = np.mean(random_array)
print("Random array of size 30=\n",random_array)
print("mean of array = \n", array_mean)

Random array of size 30=
 [0.17955057 0.56119282 0.60868433 0.1631042  0.67995077 0.19381041
 0.53527391 0.75529216 0.84052923 0.1176315  0.40564949 0.5222299
 0.51482153 0.94714619 0.54435818 0.40241154 0.77351753 0.61091542
 0.92310041 0.31369146 0.94497805 0.40551591 0.94135893 0.08414529
 0.38597667 0.67579019 0.74439571 0.68093866 0.50923364 0.56654592]
mean of array = 
 0.5510580169804865


5.Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np

random_array = np.random.rand(10, 10)

min_value = np.min(random_array)
max_value = np.max(random_array)

print("Random 10x10 Array:",random_array)
print("\nMinimum Value:", min_value)
print("Maximum Value:", max_value)

Random 10x10 Array: [[0.62206856 0.65260393 0.07716899 0.52190893 0.18048366 0.02676537
  0.93725038 0.61941992 0.10375846 0.64378573]
 [0.63059081 0.43190762 0.73734387 0.82541896 0.18835925 0.30879916
  0.57314414 0.0880603  0.8477577  0.72176556]
 [0.80843695 0.19511599 0.01538362 0.75751414 0.98391681 0.22356206
  0.69310432 0.16934262 0.57407779 0.4539815 ]
 [0.93847943 0.18436254 0.82011165 0.11940471 0.34129999 0.63929904
  0.38889685 0.64033628 0.6743421  0.90556659]
 [0.36695193 0.40346602 0.52426519 0.82909887 0.83878878 0.64525912
  0.86376356 0.42887829 0.10348631 0.52772916]
 [0.77876083 0.12537837 0.78509273 0.31276094 0.37550178 0.53670048
  0.41153875 0.51880407 0.54316662 0.23442984]
 [0.25611629 0.52307092 0.90063128 0.07382488 0.71918996 0.08122483
  0.30934702 0.30515596 0.32637757 0.48534344]
 [0.18778239 0.34110067 0.39778594 0.26478765 0.41290528 0.45704889
  0.79728303 0.56689268 0.51013313 0.01706274]
 [0.76615029 0.11926654 0.11697466 0.63057391 0.23867122 0.3

6.Create a zero array of size 10 and replace 5th element with 1

In [ ]:
import numpy as np

zero_array = np.zeros(10)
zero_array[4] = 1
print("new array=\n", zero_array)

new array=
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
import numpy as np

arr = [1,2,0,0,4,0]
reversed_array = np.array(arr)[::-1]
print("reversed array:\n", reversed_array)

reversed array:
 [0 4 0 0 2 1]


 8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np

border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("\n8. 2D Array with 1 on Border and 0 Inside:\n", border_array)


8. 2D Array with 1 on Border and 0 Inside:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


 9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

checkerboard_matrix = np.zeros((8, 8), dtype=int)
checkerboard_matrix[1::2, ::2] = 1
checkerboard_matrix[::2, 1::2] = 1
print("\n9. 8x8 Checkerboard Pattern:\n", checkerboard_matrix)


9. 8x8 Checkerboard Pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


 Problem- 3: Array Operations:
 For the following arrays:
 x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
 v = np.array([9,10]) and w = np.array([11,12]);
 Complete all the task using numpy

 1. Add the two array.
 2. Subtract the two array.
 3. Multiply the array with any integers of your choice.
 4. Find the square of each element of the array.
 5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
 6. Concatenate x(and)y along row and Concatenate v(and)w along column.
 {Hint:try np.concatenate() or np.vstack() functions.
 7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12])

add_result = x+y
print("addition=", add_result)

sub_result = x+y
print("Subtraction=", sub_result)

multiply_result = x * 5
print("Multiplication=", multiply_result)

square_result = x ** 2
print("Square Result=", square_result)

dot_vw = np.dot(v,w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("dot profuct of v and w=",dot_vw )
print("dot profuct of x and v=",dot_xv )
print("dot profuct of x and y=",dot_xy )

concat_xy = np.concatenate((x,y), axis = 1)
concat_vw = np.column_stack((v,w))
print("Concatenation of x and y along rows:\n", concat_xy)
print("Concatenation of v and w along columns:\n", concat_vw)

try:
  concat_xv = np.concatenate((x,v), axis = 0)
except ValueError as e:
    print(e)

addition= [[ 6  8]
 [10 13]]
Subtraction= [[ 6  8]
 [10 13]]
Multiplication= [[ 5 10]
 [15 25]]
Square Result= [[ 1  4]
 [ 9 25]]
dot profuct of v and w= 219
dot profuct of x and v= [29 77]
dot profuct of x and y= [[19 22]
 [50 58]]
Concatenation of x and y along rows:
 [[1 2 5 6]
 [3 5 7 8]]
Concatenation of v and w along columns:
 [[ 9 11]
 [10 12]]
all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Problem- 4: Matrix Operations:
 • For the following arrays:
 A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
 Prove following with Numpy:
 1. Prove A.A−1 = I.
 2. Prove AB= BA.
 3. Prove (AB)T = BTAT.
 • Solve the following system of Linear equation using Inverse Methods.
 2x −3y+z =−1
 x −y+2z =−3
 3x +y−z =9
 {Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
 • Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
 of Numpy}

In [ ]:
import numpy as np

A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

#1. Prove A.A−1 = I.
A_inv = np.linalg.inv(A)
identity_matrix = np.dot(A, A_inv)
print("A * A^-1:\n", identity_matrix)


# 2.Prove AB= BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("AB:\n", AB)
print("BA:\n", BA)

# 3.Prove (AB)T = BTAT

transpose_AB = np.transpose(AB)
BT_AT = np.dot(B.T, A.T)
print("(AB)^T:\n", transpose_AB)
print("B^T * A^T:\n", BT_AT)

# solving equations
coefficients = np.array([[2, -3, 1], [1, -1, 2], [3, 1, -1]])
constants = np.array([-1, -3, 9])
answer = np.linalg.solve(coefficients, constants)
print("Solutions for Linear Equations:\n", answer)


A * A^-1:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]
(AB)^T:
 [[23 51]
 [13 29]]
B^T * A^T:
 [[23 51]
 [13 29]]
Solutions for Linear Equations:
 [ 2.  1. -2.]


In [ ]:
def add_numbers(a, b):
    return a + b

# Example usage
result = add_numbers(5, 3)
print("result")

result
